message: configuration fetchd
spring:
  datasource:
    initialization-mode: always
    schema: classpath:/schema.sql
    continue-on-error: 'true'
    initialize: 'true'
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
